from __future__ import annotations

from collections.abc import Callable
from typing import Protocol

from saber_tui.autocomplete import AutocompleteProvider


class EditorComponent(Protocol):
    on_submit: Callable[[str], None] | None
    on_change: Callable[[str], None] | None

    def render(self, width: int) -> list[str]: ...

    def handle_input(self, data: str) -> None: ...

    def get_text(self) -> str: ...

    def set_text(self, text: str) -> None: ...

    def add_to_history(self, text: str) -> None: ...

    def insert_text_at_cursor(self, text: str) -> None: ...

    def get_expanded_text(self) -> str: ...

    def set_autocomplete_provider(self, provider: AutocompleteProvider) -> None: ...

    def set_padding_x(self, padding: int) -> None: ...

    def set_autocomplete_max_visible(self, max_visible: int) -> None: ...
